services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      # - loki
    networks:
      - shared-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - shared-net

  # loki:
  #   image: grafana/loki
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   networks:
  #     - shared-net

  # promtail:
  #   image: grafana/promtail
  #   container_name: promtail
  #   volumes:
  #     - ./promtail-config.yml:/etc/promtail/config.yaml
  #     - ./logs:/logs
  #   command: -config.file=/etc/promtail/config.yaml
  #   depends_on:
  #     - loki
  #   networks:
  #     - shared-net

networks:
  shared-net:
    name: shared-network # Actual name of the network created with 'docker network create'
    external: true       # This is CRUCIAL. Indicates that the network is external.

volumes:
  grafana-data:
